package com.android.xjq.utils;

import com.android.banana.commlib.http.AppParam;
import com.android.httprequestlib.BaseRequestHttpName;

/**
 * Created by zhouyi on 2017/3/29.
 */

public enum XjqUrlEnum implements BaseRequestHttpName {

    REGISTER_SEND_SMS_ACK("REGISTER_SEND_SMS_ACK", AppParam.S_URL),

    REGISTER_VALIDATE_SMS_ACK("REGISTER_VALIDATE_SMS_ACK", AppParam.S_URL),

    REGISTER("REGISTER", AppParam.S_URL),

    ONE_AUTH_LOGIN("ONE_AUTH_LOGIN", AppParam.S_URL),

    SET_DEFAULT_LOGIN_USER("SET_DEFAULT_LOGIN_USER", AppParam.S_URL),

    USER_LIST_QUERY("USER_LIST_QUERY", AppParam.S_URL),

    SEND_SMS_FOR_NOT_LOGIN("SEND_SMS_FOR_NOT_LOGIN", AppParam.S_URL),

    USER_LOGIN("USER_LOGIN", AppParam.S_URL),

    CLIENT_BANNER_QUERY("CLIENT_BANNER_QUERY", AppParam.S_URL),

    USER_LOGO_EDIT("USER_LOGO_EDIT", AppParam.S_URL),

    OAP_AUTH_LOGIN_INFO_VALIDATE("OAP_AUTH_LOGIN_INFO_VALIDATE", AppParam.S_URL),

    USER_LOGO_URL("USER_LOGO_URL", AppParam.S_URL),

    BASE_CONFIG_QUERY("BASE_CONFIG_QUERY", AppParam.S_URL),

    /***********找回密码相关***********/
    ONE_AUTH_INFO_QUERY_BY_AUTH_NAME("ONE_AUTH_INFO_QUERY_BY_AUTH_NAME", AppParam.S_URL),
    //换绑手机发送验证码至原手机号
    FIND_LOGIN_PASSWORD_BY_CELL_SET_PASSWORD("FIND_LOGIN_PASSWORD_BY_CELL_SET_PASSWORD", AppParam.S_URL),

    /***********换绑手机相关***********/
    //换绑手机验证原手机验证码
    MODIFY_BIND_CELL_SEND_OLD_CELL_SMS_ACK("MODIFY_BIND_CELL_SEND_OLD_CELL_SMS_ACK", AppParam.S_URL),
    MODIFY_BIND_CELL_VERIFY_OLD_CELL_SMS_ACK("MODIFY_BIND_CELL_VERIFY_OLD_CELL_SMS_ACK", AppParam.S_URL),
    //换绑手机发送验证码至新手机号
    MODIFY_BIND_CELL_SEND_NEW_CELL_SMS_ACK("MODIFY_BIND_CELL_SEND_NEW_CELL_SMS_ACK", AppParam.S_URL),
    //换绑手机验证新手机验证码并绑定
    MODIFY_BIND_CELL_VETIFY_NEW_CELL_SMS_ACK("MODIFY_BIND_CELL_VETIFY_NEW_CELL_SMS_ACK", AppParam.S_URL),
    /*******实名认证*********/
    USER_IDENTITY_COMPLETE("USER_IDENTITY_COMPLETE", AppParam.S_URL),

    FIND_LOGIN_PASSWORD_BY_CELL_SEND_SMS_ACK("FIND_LOGIN_PASSWORD_BY_CELL_SEND_SMS_ACK", AppParam.S_URL),

    FIND_LOGIN_PASSWORD_BY_CELL_VALIDTE_SMS_ACK("FIND_LOGIN_PASSWORD_BY_CELL_VALIDTE_SMS_ACK", AppParam.S_URL),

    /*******支付安全*********/
    PROMPT_MEMO("PROMPT_MEMO", AppParam.S_URL),

    CHANGE_ACCOUNT_PASSWORD_VALIDATE_OLD_ACCOUNT_PASSWORD("CHANGE_ACCOUNT_PASSWORD_VALIDATE_OLD_ACCOUNT_PASSWORD", AppParam.S_URL),

    ACCOUNT_PASSWORD_RULE_VALIDATE("ACCOUNT_PASSWORD_RULE_VALIDATE", AppParam.S_URL),

    CHANGE_ACCOUNT_PASSWORD("CHANGE_ACCOUNT_PASSWORD", AppParam.S_URL),

    FIND_ACCOUNT_PASSWORD_SEND_SMS_ACK("FIND_ACCOUNT_PASSWORD_SEND_SMS_ACK", AppParam.S_URL),

    FIND_ACCOUNT_PASSWORD_BY_CELL("FIND_ACCOUNT_PASSWORD_BY_CELL", AppParam.S_URL),

    FIND_ACCOUNT_PASSWORD_BY_CELL_SET_PASSWORD("FIND_ACCOUNT_PASSWORD_BY_CELL_SET_PASSWORD", AppParam.S_URL),

    INIT_ACCOUNT_PASSWORD("INIT_ACCOUNT_PASSWORD", AppParam.S_URL),

    INIT_LOGIN_PASSWORD("INIT_LOGIN_PASSWORD", AppParam.S_URL),

    /***********会员信息相关***********/
    MY_USER_INFO_QUERY("MY_USER_INFO_QUERY", AppParam.S_URL),

    MY_CHANNEL_QUERY("MY_CHANNEL_QUERY", AppParam.S_URL),

    MY_FUND_ACCOUNT_QUERY("MY_FUND_ACCOUNT_QUERY", AppParam.S_URL),

    //玩法礼物查询
    GIFT_QUERY("GIFT_QUERY", AppParam.S_URL),

    //礼物查询
    GIFT_QUERY_BY_CHANNEL_AREA_ID("GIFT_QUERY_BY_CHANNEL_AREA_ID", AppParam.S_URL),
    //根据礼物查询个数信息
    GIFT_QUERY_BY_GIFT_CONFIG_ID("GIFT_QUERY_BY_GIFT_CONFIG_ID", AppParam.S_URL),
    //礼物赠送
    GIFT_PURCHASE("GIFT_PURCHASE", AppParam.S_URL),
    //包裹赠送
    GIFT_GIVE("GIFT_GIVE", AppParam.S_URL),

    CHANNEL_LIST_QUERY("CHANNEL_LIST_QUERY", AppParam.S_URL),

    SEARCH("SEARCH", AppParam.S_URL),

    CHANNEL_USER_COUNT_QUERY_BY_CHANNEL_ID("CHANNEL_USER_COUNT_QUERY_BY_CHANNEL_ID", AppParam.S_URL),

    CHANNEL_USER_QUERY_BY_CHANNEL_ID("CHANNEL_USER_QUERY_BY_CHANNEL_ID", AppParam.S_URL),

    CHANNEL_MIC_LIST_QUERY_BY_CHANNEL_ID("CHANNEL_MIC_LIST_QUERY_BY_CHANNEL_ID", AppParam.S_URL),

    CHANNEL_MIC_COUNT_QUERY_BY_CHANNEL_ID("CHANNEL_MIC_COUNT_QUERY_BY_CHANNEL_ID", AppParam.S_URL),

    QCLOUD_TLS_USER_SIGN_ANONYMOUS_GET("QCLOUD_TLS_USER_SIGN_ANONYMOUS_GET", AppParam.S_URL),

    HOME_NAVIGATION_BAR_CONFIG("HOME_NAVIGATION_BAR_CONFIG", AppParam.S_URL),

    QCLOUD_TLS_USER_SIGN_GET("QCLOUD_TLS_USER_SIGN_GET", AppParam.S_URL),

    CHANNEL_LIST_QUERY_BY_ROOM_ID("CHANNEL_LIST_QUERY_BY_ROOM_ID", AppParam.S_URL),

    PRIZECORE_QUERY_ACTIVE_ISSUE_INFO("PRIZECORE_QUERY_ACTIVE_ISSUE_INFO", AppParam.S_URL),

    GET_RECENTLY_PRIZE_RECORD("GET_RECENTLY_PRIZE_RECORD", AppParam.S_URL),

    GIFT_EFFECT_RESOURCE_QUERY("GIFT_EFFECT_RESOURCE_QUERY", AppParam.S_URL),

    //直播间头部助威轮询接口
    CHANNEL_AREA_CHEER_GAME_BOARD_QUERY("CHANNEL_AREA_CHEER_GAME_BOARD_QUERY", AppParam.S_URL),

    //进入直播间，返回直播间有关赛事信息，主播信息等
    ENTER_CHANNEL_AREA("ENTER_CHANNEL_AREA", AppParam.S_URL),

    //频道空间在线人数，嘉宾列表轮询接口
    CHANNEL_AREA_USER_QUERY_BY_CHANNEL_AREA_ID("CHANNEL_AREA_USER_QUERY_BY_CHANNEL_AREA_ID", AppParam.S_URL),

    //助威榜单查询
    PURCHASE_ORDER_CHEER_LIST_QUERY("PURCHASE_ORDER_CHEER_LIST_QUERY", AppParam.S_URL),

    //节目下上墙栏目查询
    CHANNEL_RELATION_ON_THE_WALL_QUERY("CHANNEL_RELATION_ON_THE_WALL_QUERY", AppParam.S_URL),

    //节目下态度栏目查询
    CHANNEL_RELATION_MARKED_ATTITUDE_QUERY("CHANNEL_RELATION_MARKED_ATTITUDE_QUERY", AppParam.S_URL),

    //用户阵营选择
    CHANNEL_AREA_USER_VOTE("CHANNEL_AREA_USER_VOTE", AppParam.S_URL),

    //PK游戏局查询
    PK_GAME_BOARD_QUERY("PK_GAME_BOARD_QUERY", AppParam.S_URL),

    //PK订购
    PURCHASE_PK_NORMAL("PURCHASE_PK_NORMAL", AppParam.S_URL),

    //PK投注用户列表
    PURCHASE_USER_LIST_QUERY_BY_OPTION("PURCHASE_USER_LIST_QUERY_BY_OPTION", AppParam.S_URL),

    ENTER_CHANNEL("ENTER_CHANNEL", AppParam.S_URL),

    CHANNEL_INFO_QUERY("CHANNEL_INFO_QUERY", AppParam.S_URL),

    CLIENT_START_GRAPH_QUERY("CLIENT_START_GRAPH_QUERY", AppParam.S_URL),

    GROUP_MESSAGE_SEND("GROUP_MESSAGE_SEND", AppParam.S_URL),

    SMS_VERIFY_FOR_NOT_LOGIN("SMS_VERIFY_FOR_NOT_LOGIN", AppParam.S_URL),

    CHANNEL_AREA_USER_CHAT_CONFIG_QUERY("CHANNEL_AREA_USER_CHAT_CONFIG_QUERY", AppParam.S_URL),

    CLIENT_PROTOCOL_QUERY("CLIENT_PROTOCOL_QUERY", AppParam.S_URL),

    CHANNEL_ANONYMOUS_HEART_BEAT_SET("CHANNEL_ANONYMOUS_HEART_BEAT_SET", AppParam.S_URL),

    //心跳接口
    CHANNEL_AREA_USER_HEART_BEAT_SET("CHANNEL_AREA_USER_HEART_BEAT_SET", AppParam.S_URL),

    GIFT_SHOW_CONFIG_QUERY("GIFT_SHOW_CONFIG_QUERY", AppParam.S_URL),

    /***********红包相关***********/
    GET_COUPON_CONFIG("GET_COUPON_CONFIG", AppParam.S_URL),

    COUPON_CREATE("COUPON_CREATE", AppParam.S_URL),

    GET_ALLOW_FETCH_COUNT("GET_ALLOW_FETCH_COUNT", AppParam.S_URL),

    USER_FETCH_COUPON("USER_FETCH_COUPON", AppParam.S_URL),

    QUERY_ALLOCATED_COUPON_ITEMS("QUERY_ALLOCATED_COUPON_ITEMS", AppParam.S_URL),

    GET_COUPON_FETCH_INFO("GET_COUPON_FETCH_INFO", AppParam.S_URL),

    QUERY_AVAILABLE_COUPON("QUERY_AVAILABLE_COUPON", AppParam.S_URL),

    /***********充值相关***********/
    DEPOSIT_FUND_CHANNEL_QUERY("DEPOSIT_FUND_CHANNEL_QUERY", AppParam.S_URL),

    DEPOSIT_APPLY("DEPOSIT_APPLY", AppParam.S_URL),

    DEPOSIT_FALL_FINISH("DEPOSIT_FALL_FINISH", AppParam.S_URL),

    DEPOSIT_BASE_INFO_QUERY("DEPOSIT_BASE_INFO_QUERY", AppParam.S_URL),

    THIRD_CHANNEL_CERTIFY_INFO_QUERY("THIRD_CHANNEL_CERTIFY_INFO_QUERY", AppParam.S_URL),

    /***********贵宾席申请***********/
    VIP_SEAT_INIT("VIP_SEAT_INIT", AppParam.S_URL),

    IDENTITY_APPLY("IDENTITY_APPLY", AppParam.S_URL),

    VIP_SEAT_LIST_QUERY("VIP_SEAT_LIST_QUERY", AppParam.S_URL),

    /***********兑换金币相关***********/

    EXCHANGE_INIT("EXCHANGE_INIT", AppParam.S_URL),

    EXCHANGE_RESULT_QUERY("EXCHANGE_RESULT_QUERY", AppParam.S_URL),

    EXCHANGE_APPLY("EXCHANGE_APPLY", AppParam.S_URL),

    /***********粉丝勋章相关***********/
    USER_FANS_MEDAL_PAGE_QUERY("USER_FANS_MEDAL_PAGE_QUERY", AppParam.S_URL),

    USER_MEDAL_OPERATE("USER_MEDAL_OPERATE", AppParam.S_URL),

    USER_FANS_MEDAL_CURRENT_ADORN_INFO_QUERY("USER_FANS_MEDAL_CURRENT_ADORN_INFO_QUERY", AppParam.S_URL),

    USER_FANS_MEDAL_QUERY("USER_FANS_MEDAL_QUERY", AppParam.S_URL),

    FANS_MEDAL_INTRODUCTION("FANS_MEDAL_INTRODUCTION", AppParam.S_URL),

    FANS_RANK_MEDAL_TOTAL_QUERY("FANS_RANK_MEDAL_TOTAL_QUERY", AppParam.S_URL),

    /***********我的助威相关***********/
    PURCHASE_ORDER_SUMMARY_QUERY_BY_USER("PURCHASE_ORDER_SUMMARY_QUERY_BY_USER", AppParam.S_URL),


    PURCHASE_ORDER_SUMMARY_DETAIL_QUERY("PURCHASE_ORDER_SUMMARY_DETAIL_QUERY", AppParam.S_URL),

    /***********赛程相关***********/
    BASKETBALL_RACE_JOIN_BET_QUERY("BASKETBALL_RACE_JOIN_BET_QUERY", AppParam.S_URL),

    FOOTBALL_RACE_JOIN_SET_QUERY("FOOTBALL_RACE_JOIN_SET_QUERY", AppParam.S_URL),

    //足球
    DYNAMIC_DATA_QUERY("DYNAMIC_DATA_QUERY", com.android.banana.groupchat.AppParam.FT_API_S_URL),

    //篮球
    DYNAMIC_SCORE_DATA("DYNAMIC_SCORE_DATA", com.android.banana.groupchat.AppParam.FT_API_S_URL),

    FOOTBALL_RACE_WITH_CHANNEL_AREA_INFO_BY_DATE("FOOTBALL_RACE_WITH_CHANNEL_AREA_INFO_BY_DATE", AppParam.S_URL),
    BASKETBALL_RACE_WITH_CHANNEL_AREA_INFO_BY_DATE("BASKETBALL_RACE_WITH_CHANNEL_AREA_INFO_BY_DATE", AppParam.S_URL),


    /***********比赛***********/
    PURCHASE_FOOTBALL_NORMAL("PURCHASE_FOOTBALL_NORMAL", AppParam.S_URL),

    PURCHASE_BASKETBALL_NORMAL("PURCHASE_BASKETBALL_NORMAL", AppParam.S_URL),

    BASKETBALL_RACE_BETTING_PAGE_INFO_BY_DATE("BASKETBALL_RACE_BETTING_PAGE_INFO_BY_DATE", AppParam.S_URL),

    FOOTBALL_RACE_BETTING_PAGE_INFO_BY_DATE("FOOTBALL_RACE_BETTING_PAGE_INFO_BY_DATE", AppParam.S_URL),

    GAME_BOARD_QUERY("GAME_BOARD_QUERY", AppParam.S_URL),

    //  PURCHASE_ORDER_SUMMARY_DETAIL_QUERY("PURCHASE_ORDER_SUMMARY_DETAIL_QUERY", AppParam.S_URL),

    /***********商城***********/
    MALL_URL_QUERY("MALL_URL_QUERY", AppParam.S_URL),

    /***********主题设置威相关***********/
    THEME_QUERY("THEME_QUERY", AppParam.S_URL),

    THEME_OPERATE("THEME_OPERATE", AppParam.S_URL),


    /*香蕉球1.5期新增接口*/
    //新闻资讯
    NEWS_INFO("NEWS_INFO", AppParam.S_URL),

    //首页-伤停-足球
    RACE_INFO_AND_INJURY_QUERY("RACE_INFO_AND_INJURY_QUERY", AppParam.FT_API_S_URL),

    //首页-伤停-篮球
    INJURY_QUERY("INJURY_QUERY", AppParam.BT_API_S_URL),

    //点赞
    LIKE("LIKE", AppParam.S_URL),

    //取消点赞
    CANCEL_LIKE("CANCEL_LIKE", AppParam.S_URL),

    //首页推荐 轮播图查询
    CMS_INFO_QUERY("CMS_INFO_QUERY", AppParam.S_URL),

    //首页新鲜事
    FRESH_TOPIC("FRESH_TOPIC", AppParam.S_URL),

    //资讯详情
    CMS_INFO_DETAIL("CMS_INFO_DETAIL", AppParam.S_URL),

    //评论查询
    COMMENT_QUERY("COMMENT_QUERY", AppParam.S_URL),

    //竞彩大学
    JCDX_ARTICLE("JCDX_ARTICLE", AppParam.S_URL),

    //未读消息数
    MESSAGE_NOTICE_QUERY("MESSAGE_NOTICE_QUERY", AppParam.S_URL),

    //通知
    USER_MESSAGE_NOTICE("USER_MESSAGE_NOTICE", AppParam.S_URL),

    COMMENT_SET_TOP_OPERATE("COMMENT_SET_TOP_OPERATE", AppParam.S_URL),

    SUBJECT_DETAIL("SUBJECT_DETAIL", AppParam.S_URL),

    COMMENT_REPLY_TO_ME_MESSAGE("COMMENT_REPLY_TO_ME_MESSAGE", AppParam.S_URL),

    //推荐列表 文章
    EDITOR_RECOMMEND("EDITOR_RECOMMEND", AppParam.S_URL),

    //积分排行榜改版后接口：总榜
    TEAM_LEA_RANK_EXTRA_QUERY("TEAM_LEA_RANK_EXTRA_QUERY", AppParam.FT_API_S_URL),

    //竞彩足球积分榜
    JCZQ_TEAM_RANK_QUERY("TEAM_RANK_QUERY", AppParam.FT_API_S_URL),

    SEASON_RACE_INJURY_QUERY("SEASON_RACE_INJURY_QUERY", AppParam.FT_API_S_URL),

    //竞彩篮球积分榜
    JCLQ_TEAM_RANK_QUERY("TEAM_RANK_QUERY", AppParam.BT_API_S_URL),
    //篮球伤停
    RACE_INJURY_QUERY("RACE_INJURY_QUERY", AppParam.BT_API_S_URL),

    //节目相关
    CHANNEL_AREA_QUERY_BY_LIVE("CHANNEL_AREA_QUERY_BY_LIVE", AppParam.S_URL),

    CHANNEL_AREA_USER_ORDER_QUERY("CHANNEL_AREA_USER_ORDER_QUERY", AppParam.S_URL),

    GET_CHANNEL_AREA_QUERY("GET_CHANNEL_AREA_QUERY", AppParam.S_URL),

    CHANNEL_AREA_QUERY("CHANNEL_AREA_QUERY", AppParam.S_URL),

    //玩法

    PURCHASE_ORDER_SUMMARY_QUERY_BY_PK_USER("PURCHASE_ORDER_SUMMARY_QUERY_BY_PK_USER", AppParam.S_URL),

    ACTIVITY_PRIZE_RECORD_QUERY("ACTIVITY_PRIZE_RECORD_QUERY", AppParam.S_URL),


    //特邀嘉宾查询
    CHANNEL_AREA_GUEST_QUERY("CHANNEL_AREA_GUEST_QUERY", AppParam.S_URL),

    CHANNEL_AREA_USER_ORDER_CREATE("CHANNEL_AREA_USER_ORDER_CREATE", AppParam.S_URL),

    CHANNEL_AREA_USER_ORDER_CANCEL("CHANNEL_AREA_USER_ORDER_CANCEL", AppParam.S_URL),

    /*香蕉球二期接口*/
    //成就勋章查询
    NEWLY_ACQUIRED_ACHIEVEMENT_MEDAL_QUERY("NEWLY_ACQUIRED_ACHIEVEMENT_MEDAL_QUERY", AppParam.S_URL),

    //直播间pk进度查询
    CHANNEL_AREA_TOP_PK_GAME_BOARD_QUERY("CHANNEL_AREA_TOP_PK_GAME_BOARD_QUERY", AppParam.S_URL),
    //直播间宝箱
    USER_PACKAGE_QUERY("USER_PACKAGE_QUERY", AppParam.S_URL),

    //查询主播是否在频道
    ANCHOR_IN_CHANNEL_AREA_QUERY("ANCHOR_IN_CHANNEL_AREA_QUERY", AppParam.S_URL),

    //玩法礼物赠送接口
    PLAY_CREATE_GIFT_PURCHASE("PLAY_CREATE_GIFT_PURCHASE", AppParam.S_URL),

    //视频上传
    VIDEO_UPLOAD("VIDEO_UPLOAD", AppParam.S_URL),
    //视频配置查询
    VIDEO_CONFIG_QUERY("VIDEO_CONFIG_QUERY", AppParam.S_URL),
    //关注
    USER_FOLLOW_CREATE("USER_FOLLOW_CREATE", AppParam.S_URL),//userId
    //取消关注
    USER_FOLLOW_CANCEL("USER_FOLLOW_CANCEL", AppParam.S_URL),//userId ，userType[FOLLOWCANCEL("取消关注"),REMOVEFANS("移除粉丝")]
    //关注列表
    USER_ATTENTIONS_INFO("USER_ATTENTIONS_INFO", AppParam.S_URL),//userId,currentPage
    //粉丝列表
    USER_FANS_INFO("USER_FANS_INFO", AppParam.S_URL),//userId,currentPage
    //个人名片的查询
    GROUP_USER_INFO_QUERY("GROUP_USER_INFO_QUERY", AppParam.S_URL),//传入参数：groupId , userId
    //修改个人群名片
    GROUP_USER_INFO_MODIFY("GROUP_USER_INFO_MODIFY", AppParam.S_URL),//groupId,userId,nickName
    //我的勋章
    USER_SPECIAL_AREA_MEDAL_QUERY("USER_SPECIAL_AREA_MEDAL_QUERY", AppParam.S_URL),
    //首页动态
    MY_TOPIC_QUERY("MY_TOPIC_QUERY", AppParam.S_URL),//currentPage,showFollowers,userId
    //个人主页最新动态
    HOT_TOPIC_SUBJECT_RECOMMEND("HOT_TOPIC_SUBJECT_RECOMMEND", AppParam.S_URL),//currentPage,showFollowers,userId
    //个人主页事件
    BEHAVIOR_GENERATE_EVENT_QUERY("BEHAVIOR_GENERATE_EVENT_QUERY", AppParam.S_URL),
    //个人主页头部信息查询
    USER_INFO_QUERY("USER_INFO_QUERY", AppParam.S_URL),
    //赛程详情页  文章
    RACE_RELATION_SUBJECT_QUERY("RACE_RELATION_SUBJECT_QUERY", AppParam.S_URL),
    //赛程详情页  态度
    RACE_RELATION_MARKED_ATTITUDE_QUERY("RACE_RELATION_MARKED_ATTITUDE_QUERY", AppParam.S_URL),
    //首页推荐
    INDEX_CONTENT_RECOMMEND("INDEX_CONTENT_RECOMMEND", AppParam.S_URL),//currentPage

    //印象标签查询
    TAG_PAGE_QUERY("TAG_PAGE_QUERY", AppParam.S_URL),

    //印象标签创建
    TAG_CREATE("TAG_CREATE", AppParam.S_URL),

    //写专栏时赛事选择
    FOOTBALL_RACE_QUERY_BY_DATE("FOOTBALL_RACE_QUERY_BY_DATE", AppParam.S_URL),

    //写专栏时赛事选择
    BASKETBALL_RACE_QUERY_BY_DATE("BASKETBALL_RACE_QUERY_BY_DATE", AppParam.S_URL),


    //已加入的群聊集合查询
    USER_JOINED_GROUP_INFO_QUERY("USER_JOINED_GROUP_INFO_QUERY", AppParam.S_URL),// curpager

    //转发到个人主页时 的 查询
    TRANSMIT_CONTENT_QUERY_BEFORE_CREATE("TRANSMIT_CONTENT_QUERY_BEFORE_CREATE", AppParam.S_URL),//objectId  objectType

    //转发
    TRANSMIT_CREATE_SUBJECT("TRANSMIT_CREATE_SUBJECT", AppParam.S_URL),//objectId  objectType content

    //转发到群
    // 转发话题：objectId为话题id，objectType为SUBJECT
    //转发PK：objectId为PK游戏局id，objectType为PK_GAME_BOARD
    //转发极限手速：objectId为期次id，objectType为HAND_SPEED
    TRANSMIT_TO_GROUP("TRANSMIT_TO_GROUP", AppParam.S_URL),//groupId ,objectId,objectType

    //转发到群空间
    TRANSMIT_TO_GROUP_TOPIC("TRANSMIT_TO_GROUP_TOPIC", AppParam.S_URL),//groupIds subjectId

    //赛程详情页头部
    RACE_QUERY_BY_RACE_TYPE_AND_ID("RACE_QUERY_BY_RACE_TYPE_AND_ID", AppParam.S_URL),

    //用户默认收货地址查询
    USER_DEFAULT_RECEIVE_ADDRESS_QUERY("USER_DEFAULT_RECEIVE_ADDRESS_QUERY", AppParam.S_URL),

    //用户收货地址创建
    USER_RECEIVE_ADDRESS_CREATE("USER_RECEIVE_ADDRESS_CREATE", AppParam.S_URL),//receiverName  receiverCell provinceId cityId countyId streetInfo


    //省市区镇的查询
    PROVINCES_CITIES_COUNTS_TOWNS_QUERY("PROVINCES_CITIES_COUNTS_TOWNS_QUERY", AppParam.S_URL),//provinceId  cityId type[PROVINCE,CITY,COUNTY,TOWN]

    //省市区的查询
    PROVINCES_CITIES_COUNTS_QUERY("PROVINCES_CITIES_COUNTS_QUERY", AppParam.S_URL),//provinceId  cityId type[PROVINCE,CITY,COUNTY]

    //火箭查询
    ROCKET_QUERY("ROCKET_QUERY", AppParam.S_URL),
    //火箭参与，点火浇水
    ROCKET_PARTICIPATE("ROCKET_PARTICIPATE", AppParam.S_URL),
    //火箭结果查询
    ROCKET_PARTICIPATE_RESULT("ROCKET_PARTICIPATE_RESULT", AppParam.S_URL),

    /*********************香蕉球二期玩法接口****************************/
    //进行中游戏个数查询
    PROCESSING_GAME_QUERY("PROCESSING_GAME_QUERY", AppParam.S_URL),
    //当前活动和开始时间查询
    CURRENT_ACTIVITY_AND_GMT_START_QUERY("CURRENT_ACTIVITY_AND_GMT_START_QUERY", AppParam.S_URL),
    //极限手速查询
    HAND_SPEED_QUERY("HAND_SPEED_QUERY", AppParam.S_URL),
    //参与极限手速
    HAND_SPEED_PARTICIPATE("HAND_SPEED_PARTICIPATE", AppParam.S_URL),
    //极限手速用户中奖查询
    HAND_SPEED_USER_PRIZED_QUERY("HAND_SPEED_USER_PRIZED_QUERY", AppParam.S_URL),
    //活动期次中奖查询接口
    ACTIVITY_ISSUE_PRIZED_QUERY("ACTIVITY_ISSUE_PRIZED_QUERY", AppParam.S_URL),
    //幸运抽奖查询
    LUCKY_DRAW_QUERY("LUCKY_DRAW_QUERY", AppParam.S_URL),
    //参与幸运抽奖
    LUCKY_DRAW_PARTICIPATE("LUCKY_DRAW_PARTICIPATE", AppParam.S_URL),
    //幸运抽奖参与用户查询
    LUCKY_DRAW_PARTICIPATE_USER_QUERY("LUCKY_DRAW_PARTICIPATE_USER_QUERY", AppParam.S_URL),
    //幸运抽奖开奖查询
    LUCKY_DRAW_OPEN_DRAW_QUERY("LUCKY_DRAW_OPEN_DRAW_QUERY", AppParam.S_URL),
    //抽奖轮次信息查询
    DRAW_ROUND_INFO_QUERY("DRAW_ROUND_INFO_QUERY", AppParam.S_URL),
    //查询最近期次接口
    GET_RECENTLY_ISSUE("GET_RECENTLY_ISSUE", AppParam.S_URL),

    //额的宝箱 道具
    MY_PACKAGE_QUERY("MY_PACKAGE_QUERY", AppParam.S_URL),//type[TREASURE_CHEST ，GIFT],currentPage

    //圣旨到查询接口
    DECREE_QUERY("DECREE_QUERY", AppParam.S_URL),
    //获得圣旨到总金额接口
    GET_DECREE_TOTAL_AMOUNT("GET_DECREE_TOTAL_AMOUNT", AppParam.S_URL),
    //参与圣旨到接口
    DECREE_PARTICIPATE("DECREE_PARTICIPATE", AppParam.S_URL),

    //开宝箱
    USER_PACKAGE_OPEN("USER_PACKAGE_OPEN", AppParam.S_URL),//subTypeId ,number

    //跳web页面
    JUMP_H5_URL_QUERY("JUMP_H5_URL_QUERY", AppParam.S_URL),

    //获取兴趣标签
    USER_TAG_QUERY("USER_TAG_QUERY", AppParam.S_URL),

    //保存兴趣标签
    USER_TAG_LINK_CREATE("USER_TAG_LINK_CREATE", AppParam.S_URL),

    TEST("TEST", AppParam.S_URL);

    private String name;

    private String url;

    XjqUrlEnum(String name, String url) {
        this.name = name;
        this.url = url;
    }

    @Override
    public String getName() {
        return name;
    }

    @Override
    public String getUrl() {
        return url;
    }
}
